### ISSUE TITLE
HU001-T001: Darle funcionalidad al boton de agregar contenido en la ventana del administrador

### ISSUE THREAD

**Issue by LuisMedinaBravo** [lgsilvestre/G2_Metodologia_1_2021#1]

**Comment by AaronH12345** [comment]
Se ha diseñado la ventana del administrador y se ha programado en Java Fx. Además, parcialmente se le ha dado funcionalidad a los botones de dicha pantalla, los botones que actualmente están funcionando son el botón de agregar usuario;  botón ir a vista de usuario. También se ha insertado una tabla en dicha interfaz para en el futuro tener acceso a los registros de los usuarios existentes

![1](https://user-images.githubusercontent.com/84586249/121970791-56585880-cd45-11eb-907f-0012b1eb19d9.JPG)
