### ISSUE TITLE
HU002-T001: Darle funcionalidad al boton agregar usuario en la pantalla del administrador para el manejo de los usuarios

### ISSUE THREAD

**Issue by Sebollasnuff** [lgsilvestre/G2_Metodologia_1_2021#4]

**Comment by AaronH12345** [comment]
Se ha programado el insertar nuevos usuarios en los registro ya existentes, se esta trabajando en eliminar usuarios. En cuanto al agregar contenido y y eliminar contenido, se ha avanzado parcialmente, creando sus formularios correspondientes y recibiendo sus entradas

**Comment by AaronH12345** [comment]
![2](https://user-images.githubusercontent.com/84586249/121977876-f8337180-cd54-11eb-809e-88547ffcb303.JPG)
![3](https://user-images.githubusercontent.com/84586249/121977895-01244300-cd55-11eb-924b-37829064300a.JPG)
![4](https://user-images.githubusercontent.com/84586249/121977935-14cfa980-cd55-11eb-8c89-04fed7851f2f.JPG)
